<a href="https://colab.research.google.com/github/karltristanromero/Aimdex_finger_game/blob/main/numpy_array_2d_stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **NumPy**

#### *Making Arrays*
- **array()**
- Ex: np.array(list_name)

In [1]:
import numpy as np
# Test change
list_num = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

num_array = np.array(list_num)

num_array *= 2

print(num_array)

[ 2  4  6  8 10 12 14 16 18 20]


#### *NumPy Array Subsetting*

- Similar to indexing
- To pick only a certain subset from an array.

In [ ]:
# This code makes an array from a subset. Basically, it (1) take a subset
# based on the condition, then (2) place them into another array.

num_array[num_array % 3 == 0]

### **Types of NumPy Array**

#### 2D NumPy Array

- It has columns and rows.
- Ex.:([[1.73, 1.68, 1.71, 1.89, 1.79],    *#First Row*  <br>
            [65.4, 59.2, 63.6, 88.4, 68.7]])   *#Second Row*

In [2]:
# Make a 2D Array then determine its shape using .shape()

np_2D = np.array([[1, 2, 3.4, 4.56, 7, 0.23, 90],
                 [6.7, 1, 10, 12, 94, 11, 56.6]])

print(np_2D.shape) # Prints number of (rows, columns)

(2, 7)


In [5]:
# Subsetting the first row

print(np_2D[0])

[ 1.    2.    3.4   4.56  7.    0.23 90.  ]


In [6]:
# Subsetting row and columns

# First Method

print("First Method: ")
print(np_2D[0][3])

# Second Method
print("Second Method: ")
print(np_2D[0, 3])

# Use power of Colons to specify range

print("Print all rows from column index 1-2: ")
print(np_2D[:, 1:3])

print("Print all records in row 1: ")
print(np_2D[1:, :])

First Method: 
4.56
Second Method: 
4.56
Print all rows from column index 1-2: 
[[ 2.   3.4]
 [ 1.  10. ]]
Print all records in row 1: 
[[ 6.7  1.  10.  12.  94.  11.  56.6]]


### Using NumPy's Statistical Methods

- Including: **mean()**, **median()**, **corrcoef()**, **std()**, **round()**, **sum()**, **sort()**, **random.normal()**, **columm_stack()**

In [7]:
# Use mean() function of NumPy

print("Print the mean of all values")
print(np.mean(np_2D))


print("Print the mean of values in row 1")
print(np.mean(np_2D[0, :]))

print("Print the mean of values row 0 and 1 in column 0")
print(np.mean(np_2D[:, 0]))

Print the mean of all values
21.392142857142858
Print the mean of values in row 1
15.455714285714285
Print the mean of values row 0 and 1 in column 0
3.85


In [8]:
# Use median() function of NumPy

print("Print the median of all values")
print(np.median(np_2D))

print("Print the median of values in row 1")
print(np.median(np_2D[0, :]))

print("Print the median of values row 0 and 1 in column 0")
print(np.median(np_2D[:, 0]))

Print the median of all values
6.85
Print the median of values in row 1
3.4
Print the median of values row 0 and 1 in column 0
3.85


In [11]:
# Other way to call for the aggregate values
print(np_2D[0][:].mean())

15.455714285714285


In [12]:
# Use corrcoef (or correlation coefficient) of TWO 1D Arrays

print("Print the correlated coefficient of values in both rows")
print(np.corrcoef(np_2D)[0, 1])

print("Set the corrcoeff of values in a variable")
corr_coeff_array = np.corrcoef(np_2D)
print(corr_coeff_array)

print("Print the correlated coefficient of values in row 1")
print(corr_coeff_array[1, :])
print(np.corrcoef(np_2D)[1, :])

Print the correlated coefficient of values in both rows
0.42209814371442467
Set the corrcoeff of values in a variable
[[1.         0.42209814]
 [0.42209814 1.        ]]
Print the correlated coefficient of values in row 1
[0.42209814 1.        ]
[0.42209814 1.        ]


### **Comparison Operators on arrays**

In [ ]:
import numpy as np

In [13]:
# Set BMI
bmi = [24.98, 26.23, 21.09, 30.12, 18.52, 27.76, 22.86, 25.00, 29.63, 23.44]

In [14]:
# Convert BMI into array
bmi_arr = np.array(bmi)
print(bmi_arr)

[24.98 26.23 21.09 30.12 18.52 27.76 22.86 25.   29.63 23.44]


In [15]:
# Compare each element of the array to a number

bmi_arr > 25

array([False,  True, False,  True, False,  True, False, False,  True,
       False])

#### **Logical_and**, **logical_or**, **logical_not**

In [22]:
print(bmi_arr)
np.logical_and(bmi_arr > 21, bmi_arr < 22)

[24.98 26.23 21.09 30.12 18.52 27.76 22.86 25.   29.63 23.44]


array([False, False,  True, False, False, False,  True, False, False,
        True])

In [23]:
bmi_arr[np.logical_or(bmi_arr > 21, bmi_arr < 22)]

array([24.98, 26.23, 21.09, 30.12, 18.52, 27.76, 22.86, 25.  , 29.63,
       23.44])